# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
